name: slack notifying 
on:
    push:  
        branches: 
            - main 
            - 'feature/*'  
jobs:
  
  unit_test:  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies 
        run: npm install 

      - name: Run Unit Tests
        id: nodejs-unit-test-step
        run: npm test
        
  notify:
      runs-on: ubuntu-latest
      needs: unit_test
      if: always()
      steps:
        - name: Check Unit Test Result
          run: |
            if [ "${{needs.unit_test.results}}" = "failure" ]; then
                      echo "Unit tests failed! Sending notification..."
                      else
                           echo "Unit tests passed! Skipping notification."
            fi

          
        - name: Send Slack Notification
          uses: rtCamp/action-slack-notify@v2
          env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}  
            SLACK_MESSAGE: " Workflow which name is ${{ github.workflow }} ${{ job.status }}`!"
            SLACK_COLOR: danger          