name: notify
on:
    push:  
        branches: 
            - main 
            - 'feature/*'  
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Send Slack Notification
          uses: rtCamp/action-slack-notify@v2
          env:
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}  # بنستخدم الـ Secret اللي أضفناه
            SLACK_MESSAGE: " Workflow `${{ github.workflow }}` انتهى بحالة `${{ job.status }}`!"
            SLACK_COLOR: ${{ job.status == 'success' && 'good' || 'danger' }}            