name: test kubernates 
on: 
    push 
jobs:
    test_k8s:
        runs-on: ubuntu-latest  
        steps:
            - name: install kubectl
              uses: azure/setup-kubectl@v4
              with:
               version: 'v1.30.0'
            - name: Set Kubeconfig
              run: | 
                  mkdir -p $HOME/.kube 
                  echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config
                  chmod 600 $HOME/.kube/config
                  export KUBECONFIG=$HOME/.kube/config
                  export KUBECONFIG=$PWD/kubeconfig.yaml
          
            - name: fetch kubernates cluster detailes 
              run: |
                kubectl get nodes
                echo >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
                kubectl version     
