name: test kubernates 
on: 
    push 
jobs:
    test_k8s:
        runs-on: ubuntu-latest  
        steps:
            - name: install kubectl
              uses: azure/setup-kubectl@v4
              with:
               version: 'v1.30.0'
            - name: Set Kubeconfig
              run: |
                 echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
                 export KUBECONFIG=$PWD/kubeconfig.yaml
          
            - name: fetch kubernates cluster detailes 
              run: |
                kubectl get nodes
                echo >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
                kubectl version     
